font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

background_opacity       0.8
background_blur          1
window_padding_width     5
hide_window_decorations  yes
remember_window_size     no
confirm_os_window_close  0

window_border_width      1.0pt
active_border_color      #0055ff
inactive_border_color    #00aaff

cursor_shape             block
cursor_blink_interval    0
cursor_trail 			 15
cursor_trail_decay       0.1 0.3
cursor_trail_start_threshold 0
cursor #00ffff

map ctrl+shift+enter     new_window
map ctrl+shift+w         close_window
map ctrl+shift+e 	 	 next_layout 

map ctrl+shift+h         neighboring_window left
map ctrl+shift+l         neighboring_window right
map ctrl+shift+k         neighboring_window up
map ctrl+shift+j         neighboring_window down

map ctrl+alt+h           resize_window narrower
map ctrl+alt+l           resize_window wider
map ctrl+alt+k           resize_window taller
map ctrl+alt+j           resize_window shorter
map ctrl+alt+r           resize_window reset

map ctrl+alt+f toggle_layout stack

map page_up scroll_page_up
map page_down scroll_page_down
map ctrl+shift+0 change_font_size all 0
