
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "pcmanfm"
local menu        = "rofi -show drun"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal) hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function ()
  hl.exec_cmd("cbatticon")
  hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("awww-daemon & sleep 0.5 && ~/.config/hypr/scripts/wallpapers.sh loop &")
  hl.exec_cmd("waybar") 
  hl.exec_cmd("~/.config/hypr/bt-volume-fix.sh") 
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_USE_PORTAL", "1")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
		   	enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

hl.curve("workFast", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })

hl.animation({ leaf = "global",        enabled = true,  speed = 4.0, bezier = "workFast" })
hl.animation({ leaf = "border",        enabled = false }) 

hl.animation({ leaf = "windows",       enabled = true,  speed = 3.5, bezier = "workFast" })
hl.animation({ leaf = "windowsIn",      enabled = true,  speed = 3.5, bezier = "workFast" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 3.0, bezier = "workFast" }) 
hl.animation({ leaf = "windowsMove",   enabled = true,  speed = 4.0, bezier = "workFast" })

hl.animation({ leaf = "fade",          enabled = true,  speed = 3.0, bezier = "workFast" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 3.0, bezier = "workFast" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 2.5, bezier = "workFast" })

hl.animation({ leaf = "layers",        enabled = true,  speed = 3.5, bezier = "workFast" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 3.5, bezier = "workFast" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 3.0, bezier = "workFast" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 3.0, bezier = "workFast" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 2.5, bezier = "workFast" })

hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4.0, bezier = "workFast" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 4.0, bezier = "workFast" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 4.0, bezier = "workFast" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 4.0, bezier = "workFast" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

hl.layer_rule({
    name = "rofi-slide-bottom",
    match = { namespace = "^rofi$" },
    animation = "slide bottom",
})

hl.layer_rule({
    name = "rofi-fullscreen-dim-blur",
    match = { namespace = "^rofi$" },
    dim_around = true,
    blur = true,
})

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = true, -- If true disables the random hyprland logo / anime girl background. :(
		disable_splash_rendering = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us, ru",
        kb_variant = "",
        kb_model   = "",
        kb_options = "grp:alt_shift_toggle",
        kb_rules   = "",

		repeat_rate = 30,
		repeat_delay = 300,

        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + Y", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + V", hl.dsp.layout("togglesplit"))    
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal .. " yazi"))

hl.bind(mainMod .. " + G", function()
    hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
    hl.dispatch(hl.dsp.window.resize({ x = 900, y = 600 }))
	hl.dispatch(hl.dsp.window.center())
end)

hl.bind("ALT + Tab", hl.dsp.window.cycle_next())

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J",  hl.dsp.focus({ direction = "down" }))

-- Move windows with mainMod + SHIFT + H/J/K/L
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))

-- Resize windows with mainMod + U/I/O/P
local resizeStep = 30

hl.bind(mainMod .. " + U", hl.dsp.window.resize({ x = -resizeStep, y = 0,            relative = true }), { repeating = true })
hl.bind(mainMod .. " + I", hl.dsp.window.resize({ x = 0,           y = -resizeStep,  relative = true }), { repeating = true })
hl.bind(mainMod .. " + O", hl.dsp.window.resize({ x = 0,           y = resizeStep,   relative = true }), { repeating = true })
hl.bind(mainMod .. " + P", hl.dsp.window.resize({ x = resizeStep,  y = 0,            relative = true }), { repeating = true })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl set +750"),                  	   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl set 750-"),                  	   { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Print Screen
hl.bind("Print", hl.dsp.exec_cmd('grim -g "$(slurp)" - | swappy -f -'))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd('grim - | swappy -f -'))

-- PowerMenu
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("~/.config/rofi/scripts/powermenu.sh"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("systemctl reboot"))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd("systemctl poweroff"))

-- Change Wallpaper
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpapers.sh"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("~/.config/rofi/scripts/wallmenu.sh"))

-- Change Window
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("~/.config/rofi/scripts/rofi-move.sh"))

-- Mouse Movement
local mouseStep = 10

hl.bind(mainMod .. " + CTRL + H", hl.dsp.exec_cmd("ydotool mousemove -x -" .. mouseStep .. " -y 0"), { repeating = true })
hl.bind(mainMod .. " + CTRL + J", hl.dsp.exec_cmd("ydotool mousemove -x 0 -y " .. mouseStep), { repeating = true })
hl.bind(mainMod .. " + CTRL + K", hl.dsp.exec_cmd("ydotool mousemove -x 0 -y -" .. mouseStep), { repeating = true })
hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("ydotool mousemove -x " .. mouseStep .. " -y 0"), { repeating = true })

hl.bind(mainMod .. " + CTRL + F", hl.dsp.exec_cmd("ydotool click 0xC0")) 
hl.bind(mainMod .. " + CTRL + D", hl.dsp.exec_cmd("ydotool click 0xC1"))

-- Cool Retro Terminal
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("cool-retro-term"))

-- Rofi Filebrowser
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("rofi -show filebrowser -filebrowser-directory ~")) 

-- Rofi Wifi and Bluetooth
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("~/.config/rofi/scripts/rofi-wifi.sh")) 
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/.config/rofi/scripts/rofi-bluetooth.sh"))

-- Btop Bind
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(terminal .. " -e btop"))

-- Music Bind
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("audacious"))

-- Waybar Bind
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("~/.config/waybar/toggle-style.sh"))

-- Rofi Theme Selector
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("~/.config/rofi/scripts/theme-selector.sh"))

-- Rofimoji Bind
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("rofimoji --selector rofi --clipboarder wl-copy --typer wtype"))

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
