background {
    monitor =
    path = ~/Pictures/hyperland_girl.png
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgb(0, 242, 254)
    font_size = 70
    font_family = JetBrains Mono Bold
    position = 0, 120
    halign = center
    valign = center
    
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgb(0, 0, 0)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgb(0, 110, 255)
    font_size = 20
    font_family = JetBrains Mono
    position = 0, 190
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3 
    dots_center = true
    dots_fade_time = 100
    
    outer_color = rgb(0, 242, 254)
    inner_color = rgba(10, 12, 16, 0.95)
    font_color = rgb(0, 110, 255)
    
    fail_color = rgb(255, 46, 99)
    fail_text = <i>Incorrect password ($ATTEMPTS)</i>
    fail_transition = 200
    
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    
    position = 0, -40
    halign = center
    valign = center
}
